name: build
on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install Cross binutils
      run: |
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        for i in linux-amd64 linux-arm64; do
          if [ "$i" = "linux-arm64" ]; then
            buildenv="CC=aarch64-linux-gnu-gcc"
          else
            buildenv=""
          fi
          env $buildenv make ARCH=$i all
          tar -cz --numeric-owner --owner root --group root -f tunaccount-$i-bin.tar.gz -C build-$i tunaccount
        done

    - name: Keep artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 'tunaccount-linux-arm64'
        path: 'tunaccount-linux-arm64-bin.tar.gz'

    - name: Keep artifacts
      uses: actions/upload-artifact@v2
      with:
        name: 'tunaccount-linux-amd64'
        path: 'tunaccount-linux-amd64-bin.tar.gz'

